### ISSUE TITLE
TODO Day 2

### ISSUE THREAD

**Issue by nidup** [nidup/ldjam42#1]
- [x] sprite hero 
 - [x] band sprite & animation
 - [x] people arrive by waves (during the concert)
 - [x] create and add favicon
 - [x] start music only when play (export beepbox sound as ogg)
 - [x] introduce sounds manager
 - [x] add voice related to public events
 - [x] add player sorry o sorry sounds
 - [x] add text and or visible area zone (colored?) to make sure the player knows what he needs to do, where he needs to go
 - [x] score mecanism (how you earn points)
 - [x] UI score and energy jauge (no more energy, no way to spam the space key)
- [x] fix hero broken animation when being pushed back
- [x] fix citizen passing through the barreer near the pit
- [x] Fix random move to get only places where there is nobody
- [x] more visible player
- [x] add voice related to scenario (wall of death, circle pit)

Mandatory
- [x] create and add splash screen (explain keys + ask to add sound + explain game)
- [x] add effect related to earned points or event (screen shaking, blinking) for more user feedback
- [x] end of game need to go out because another concert is starting, score display, replay, etc
- [x] Fix bug on out

Marketing
- [x] Polish entry and submit
- [x] Remove not used assets to shrink the build
- [x] Upload on ich and test!

Possible upgrade
- [x] add several voice for each sentence
- [x] big blinking/shaking text when starting circle pit, wall of death
- [x] add big text with blinking camera for circle pit and wall of the death?
- [x] Fix Wall Of Death fight position
- [x] Add icono for points + power
- [x] Do several people
- [x] Share your score on twitter
